#!/bin/sh
#
# Copyright 2001-2002 Double Precision, Inc.  See COPYING for
# distribution information.

srcfile="$1"
dstfile="$2"

if test ! -f $srcfile
then
	echo "$srcfile: not found" >&2
	exit 1
fi

rm -rf $dstfile.tmpdir
mkdir -p $dstfile.tmpdir

DOCBOOK_XSL=""
# sgml/docbook/xsl-stylesheets used by Fedora, xml/docbook/stylesheet by Debian/Ubuntu
for xslfile in /usr/share/sgml/docbook/xsl-stylesheets/manpages/docbook.xsl /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl; do
 if [ -f "$xslfile" ]; then
   DOCBOOK_XSL="$xslfile"
   break
 fi
done
if [ -z "$DOCBOOK_XSL" ]; then
 echo >&2 docbook.xsl stylesheet not found. Please edit docbook/sgml2man
 exit 1
fi

xsltproc --nonet -o $dstfile.tmpdir/ "$DOCBOOK_XSL" $srcfile

for f in $dstfile.tmpdir/*
do
    sed -n '1p' <$f >$dstfile.tmp
    sed -n '20,$d;/<!--/p' <$srcfile | sed 's/\"/ /g;s/^/\.\\\"/g' >>$dstfile.tmp || exit 1

    sed '1d' <$f >>$dstfile.tmp || exit 1
    mv $dstfile.tmp `basename $f` || exit 1
done

rm -rf $dstfile.tmpdir
#`dirname $0`/fixman "$srcfile" "$dstfile"
