#!/bin/sh

LC_ALL=C
export LC_ALL

doit() {

	if test ! -f configure.ac
	then
	    for d in */.
	    do
		( cd $d >/dev/null 2>&1 || continue; doit ) || exit 1
	    done
	    exit 0
	fi

echo `pwd`:

	if test -f po/Makevars
	then
		rm -rf backup
		mkdir backup
		if test -f ChangeLog
		then
			mv ChangeLog backup
		fi
		mv configure.ac Makefile.am backup
		cp backup/* .
		sed 's@dev/tty@dev/null@' <`which gettextize` >fixed
		sh fixed -f
		rm -f ABOUT-NLS ChangeLog fixed
		mv backup/* .
		rmdir backup
	fi

	if grep -q LT_INIT configure.ac
	then
		libtoolize --force --copy `if grep -q LIBLTDL configure.ac ; then echo --ltdl; fi`
	else
	    if grep -q PROG_LIBTOOL configure.ac
	    then
		libtoolize --force --copy `if grep -q LIBLTDL configure.ac ; then echo --ltdl; fi`
	    fi
	fi
	aclocal || exit 1
	if grep -q [AM\|AC]_CONFIG_HEADER configure.ac
	then
		autoheader || exit 1
	fi
	if grep -q AC_PROG_SYSCONFTOOL configure.ac
	then
		sysconftoolize || exit 1
	fi
	for gitfile in $(find . -maxdepth 1 -name "*.in.git" -type f)
	do
		gitfile_dist=$(basename $gitfile ".git")
		cp $gitfile $gitfile_dist
	done
	if test -f AUTHORS -a -f NEWS -a -f README
	then
		automake --add-missing || exit 1
	else
		automake --foreign --add-missing || exit 1
	fi
	autoconf || exit 1

	grep '^subdirs=' <configure >configure.tmp
	subdirs=
	. ./configure.tmp
	rm configure.tmp
	subdirs="`echo $subdirs`"
	if test "$subdirs" = ""
	then
		subdirs="`echo */.`"
	fi
	for d in $subdirs
	do
	    if test -f "$d/configure.ac"
	    then
		( cd $d >/dev/null 2>&1 || continue; doit ) || exit 1
	    fi
	done
}

doit
